galaxy_info:
  role_name: common
  namespace: escalate
  author: Felix Boerner
  description: Manage basic operating system configuration on Raspberry Pi OS
  license: MIT
  min_ansible_version: 2.10
  github_branch: master
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - raspberry
    - pi
    - raspberrypi
    - common
    - hostname
    - timezone
    - apt
dependencies: []
