galaxy_info:
  role_name: timesyncd
  namespace: escalate
  author: Felix Boerner
  description: Manage systemd-timesyncd on Raspberry Pi OS
  license: MIT
  min_ansible_version: 2.10
  github_branch: master
  platforms:
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - raspberry
    - pi
    - raspberrypi
    - systemd
    - timesyncd
dependencies: []
