galaxy_info:
  role_name: promtail
  namespace: escalate
  author: Felix Boerner
  description: Manage Promtail Docker container with systemd on Raspberry Pi OS
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - raspberry
    - pi
    - raspberrypi
    - systemd
    - docker
    - container
    - promtail
    - loki
    - log
    - logs
    - logfile
    - logfiles
    - logging
dependencies: []
